.NVM0
; Generated by Perano Language Compiler

; Function: main
fn_main:
    ; call ret
    push 42
    call32 fn_ret
    ; Main returns 0 by default
    push 0
    syscall exit
    ret

; Function: ret
fn_ret:
    ; param: exitcode -> local 0
    ; inline asm
    load 0
    syscall exit
    ret

